export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_ORDER = 'ADD_ORDER';
export const UPDATE_INVENTORY = 'UPDATE_INVENTORY';
export const CLOSE_ORDER_MODAL = 'CLOSE_ORDER_MODAL';
export const OPEN_ORDER_MODAL = 'OPEN_ORDER_MODAL';
export const CLOSE_PRODUCT_MODAL = 'CLOSE_PRODUCT_MODAL';
export const OPEN_PRODUCT_MODAL = 'OPEN_PRODUCT_MODAL';